### ISSUE TITLE
Stacktrace when stopping aptly

### ISSUE THREAD

**Issue by lbolla** [molior-dbs/aptly#4]
When stopping aptly, the below stack trace is printed.

```
Aug 19 17:10:12 hostname systemd[1]: Stopping Aptly REST API service...
Aug 19 17:10:12 hostname aptly[14360]: SIGQUIT: quit
Aug 19 17:10:12 hostname aptly[14360]: PC=0x45b941 m=0 sigcode=0
Aug 19 17:10:12 hostname aptly[14360]: goroutine 0 [idle]:
Aug 19 17:10:12 hostname aptly[14360]: runtime.futex(0x13ab1a0, 0x80, 0x0, 0x0, 0x7ffd00000000, 0x0, 0x0, 0x0, 0x7ffdf6edaa20, 0x40c3e2, ...)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/runtime/sys_linux_amd64.s:531 +0x21
Aug 19 17:10:12 hostname aptly[14360]: runtime.futexsleep(0x13ab1a0, 0x100000000, 0xffffffffffffffff)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/runtime/os_linux.go:46 +0x4b
Aug 19 17:10:12 hostname aptly[14360]: runtime.notesleep(0x13ab1a0)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/runtime/lock_futex.go:151 +0xa2
Aug 19 17:10:12 hostname aptly[14360]: runtime.stopm()
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/runtime/proc.go:2016 +0xe3
Aug 19 17:10:12 hostname aptly[14360]: runtime.findrunnable(0xc00002a000, 0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/runtime/proc.go:2487 +0x4dc
Aug 19 17:10:12 hostname aptly[14360]: runtime.schedule()
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/runtime/proc.go:2613 +0x13a
Aug 19 17:10:12 hostname aptly[14360]: runtime.park_m(0xc000312300)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/runtime/proc.go:2676 +0xae
Aug 19 17:10:12 hostname aptly[14360]: runtime.mcall(0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/runtime/asm_amd64.s:299 +0x5b
Aug 19 17:10:12 hostname aptly[14360]: goroutine 1 [IO wait, 8 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: internal/poll.runtime_pollWait(0x7fba8a2e7f00, 0x72, 0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/runtime/netpoll.go:173 +0x66
Aug 19 17:10:12 hostname aptly[14360]: internal/poll.(*pollDesc).wait(0xc000197398, 0x72, 0xc009b5ab00, 0x0, 0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:85 +0x9a
Aug 19 17:10:12 hostname aptly[14360]: internal/poll.(*pollDesc).waitRead(0xc000197398, 0xffffffffffffff00, 0x0, 0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Aug 19 17:10:12 hostname aptly[14360]: internal/poll.(*FD).Accept(0xc000197380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/internal/poll/fd_unix.go:384 +0x1a0
Aug 19 17:10:12 hostname aptly[14360]: net.(*netFD).accept(0xc000197380, 0x0, 0xde3ca6, 0xf9)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/net/fd_unix.go:238 +0x42
Aug 19 17:10:12 hostname aptly[14360]: net.(*TCPListener).accept(0xc00009ca68, 0xc000365a40, 0xa798b489, 0x79054c2c2f83cb82)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/net/tcpsock_posix.go:139 +0x2e
Aug 19 17:10:12 hostname aptly[14360]: net.(*TCPListener).AcceptTCP(0xc00009ca68, 0xc000365a68, 0x480836, 0x611e725f)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/net/tcpsock.go:247 +0x47
Aug 19 17:10:12 hostname aptly[14360]: net/http.tcpKeepAliveListener.Accept(0xc00009ca68, 0xc000365ab8, 0x18, 0xc000000300, 0x6ea7c5)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/net/http/server.go:3232 +0x2f
Aug 19 17:10:12 hostname aptly[14360]: net/http.(*Server).Serve(0xc0002ce0d0, 0xdf9a20, 0xc00009ca68, 0x0, 0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/net/http/server.go:2826 +0x22f
Aug 19 17:10:12 hostname aptly[14360]: net/http.(*Server).ListenAndServe(0xc0002ce0d0, 0xc0002ce0d0, 0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/net/http/server.go:2764 +0xb6
Aug 19 17:10:12 hostname aptly[14360]: net/http.ListenAndServe(0xc000201d10, 0xe, 0xdf2460, 0xc00024b8c0, 0x0, 0x42)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/net/http/server.go:3004 +0x74
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/cmd.aptlyAPIServe(0xc00024b560, 0xc0001f95b0, 0x0, 0x0, 0x0, 0x0)

Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/net/http/server.go:2826 +0x22f
Aug 19 17:10:12 hostname aptly[14360]: net/http.(*Server).ListenAndServe(0xc0002ce0d0, 0xc0002ce0d0, 0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/net/http/server.go:2764 +0xb6
Aug 19 17:10:12 hostname aptly[14360]: net/http.ListenAndServe(0xc000201d10, 0xe, 0xdf2460, 0xc00024b8c0, 0x0, 0x42)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/net/http/server.go:3004 +0x74
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/cmd.aptlyAPIServe(0xc00024b560, 0xc0001f95b0, 0x0, 0x0, 0x0, 0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/cmd/api_serve.go:95 +0x248
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc00024b560, 0xc0001f95b0, 0x0, 0x0, 0xc0002bbe40, 0x57190a)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:305 +0x27f
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc00024b680, 0xc0001f95b0, 0x1, 0x1, 0x8, 0xd1d540)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:283 +0x133
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc00024b7a0, 0xc0001f95a0, 0x2, 0x2, 0xc0002bf500, 0xc0001f95a0)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:283 +0x133
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/cmd.Run(0xc00024b7a0, 0xc00009e130, 0x5, 0x5, 0xc0002bbf01, 0x0)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/cmd/run.go:41 +0x1fd
Aug 19 17:10:12 hostname aptly[14360]: main.main()
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/main.go:24 +0x123
Aug 19 17:10:12 hostname aptly[14360]: goroutine 20 [syscall, 5907 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: os/signal.signal_recv(0x53fd33)
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/runtime/sigqueue.go:139 +0x9c
Aug 19 17:10:12 hostname aptly[14360]: os/signal.loop()
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/os/signal/signal_unix.go:23 +0x22
Aug 19 17:10:12 hostname aptly[14360]: created by os/signal.init.0
Aug 19 17:10:12 hostname aptly[14360]:         /usr/lib/go-1.11/src/os/signal/signal_unix.go:29 +0x41
Aug 19 17:10:12 hostname aptly[14360]: goroutine 36 [select]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc0003300e0)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x12a
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x177
Aug 19 17:10:12 hostname aptly[14360]: goroutine 50 [select, 26 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0000c04e0)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0xd3
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb.openDB
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/db.go:141 +0x40c
Aug 19 17:10:12 hostname aptly[14360]: goroutine 51 [select, 2 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0000c04e0)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:101 +0xe7
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb.openDB
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/db.go:142 +0x42e
Aug 19 17:10:12 hostname aptly[14360]: goroutine 52 [select, 26 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0000c04e0)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x242
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb.openDB
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x58c
Aug 19 17:10:12 hostname aptly[14360]: goroutine 53 [select, 204 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0000c04e0)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x12e

Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:501 +0x38
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:500 +0x12f
Aug 19 17:10:12 hostname aptly[14360]: goroutine 451 [chan receive, 5900 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals.func1(0xc016282d80, 0xc0001260c0, 0xc0128cdee0)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:501 +0x38
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:500 +0x12f
Aug 19 17:10:12 hostname aptly[14360]: goroutine 759 [chan receive, 5886 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/console.(*Progress).worker(0xc0254e0c80)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/console/progress.go:180 +0x7d
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/console.(*Progress).Start
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/console/progress.go:54 +0x3f
Aug 19 17:10:12 hostname aptly[14360]: goroutine 68425 [chan receive, 4387 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals.func1(0xc020b9a540, 0xc0001260c0, 0xc02220c440)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:501 +0x38
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:500 +0x12f
Aug 19 17:10:12 hostname aptly[14360]: goroutine 68146 [chan receive, 4394 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals.func1(0xc06604a6c0, 0xc0001260c0, 0xc065a9d750)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:501 +0x38
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:500 +0x12f
Aug 19 17:10:12 hostname aptly[14360]: goroutine 177969 [chan receive, 208 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals.func1(0xc059484b40, 0xc0001260c0, 0xc04717b820)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:501 +0x38
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:500 +0x12f
Aug 19 17:10:12 hostname aptly[14360]: goroutine 68133 [chan receive, 4394 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals.func1(0xc038848540, 0xc0001260c0, 0xc0154e4320)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:501 +0x38
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:500 +0x12f
Aug 19 17:10:12 hostname aptly[14360]: goroutine 178169 [chan receive, 205 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals.func1(0xc03683eba0, 0xc0001260c0, 0xc01989e480)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:501 +0x38
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:500 +0x12f
Aug 19 17:10:12 hostname aptly[14360]: goroutine 177953 [chan receive, 208 minutes]:
Aug 19 17:10:12 hostname aptly[14360]: github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals.func1(0xc03ad85020, 0xc0001260c0, 0xc05d43a020)
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:501 +0x38
Aug 19 17:10:12 hostname aptly[14360]: created by github.com/aptly-dev/aptly/context.(*AptlyContext).GoContextHandleSignals
Aug 19 17:10:12 hostname aptly[14360]:         /home/admin/src/aptlydeb/src/github.com/aptly-dev/aptly/context/context.go:500 +0x12f

Aug 19 17:10:12 hostname aptly[14360]: rax    0xca
Aug 19 17:10:12 hostname aptly[14360]: rbx    0x13ab060
Aug 19 17:10:12 hostname aptly[14360]: rcx    0x45b943
Aug 19 17:10:12 hostname aptly[14360]: rdx    0x0
Aug 19 17:10:12 hostname aptly[14360]: rdi    0x13ab1a0
Aug 19 17:10:12 hostname aptly[14360]: rsi    0x80
Aug 19 17:10:12 hostname aptly[14360]: rbp    0x7ffdf6eda9e8
Aug 19 17:10:12 hostname aptly[14360]: rsp    0x7ffdf6eda9a0
Aug 19 17:10:12 hostname aptly[14360]: r8     0x0
Aug 19 17:10:12 hostname aptly[14360]: r9     0x0
Aug 19 17:10:12 hostname aptly[14360]: r10    0x0
Aug 19 17:10:12 hostname aptly[14360]: r11    0x286
Aug 19 17:10:12 hostname aptly[14360]: r12    0x1
Aug 19 17:10:12 hostname aptly[14360]: r13    0xc00032a060
Aug 19 17:10:12 hostname aptly[14360]: r14    0xc00001e240
Aug 19 17:10:12 hostname aptly[14360]: r15    0x2
Aug 19 17:10:12 hostname aptly[14360]: rip    0x45b941
Aug 19 17:10:12 hostname aptly[14360]: rflags 0x286
Aug 19 17:10:12 hostname aptly[14360]: cs     0x33
Aug 19 17:10:12 hostname aptly[14360]: fs     0x0
Aug 19 17:10:12 hostname aptly[14360]: gs     0x0
Aug 19 17:10:12 hostname systemd[1]: aptly.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 19 17:10:12 hostname systemd[1]: aptly.service: Failed with result 'exit-code'.
Aug 19 17:10:12 hostname systemd[1]: Stopped Aptly REST API service.
```

**Comment by lbolla** [comment]
I managed to reproduce the issue by killing `aptly api serve` with `kill -quit <pid>`. Using any other signal doesn't print the stacktrace. SIGQUIT is what systemd uses in the aptly service.

**Comment by lbolla** [comment]
@neolynx Do you know a reason why we should deviate from systemd standard kill signal (sigterm) to kill the aptly service and use sigquit, which causes the above stacktrace?

See https://github.com/molior-dbs/aptlydeb/blob/feature/aptly-1.4.0/debian/aptly.service#L9

**Comment by neolynx** [comment]
I do not see why a SIGQUIT should be used, even for command mode of aptly. I would opt for changing this to normal behavior...

**Comment by lbolla** [comment]
Fixed in https://github.com/molior-dbs/aptlydeb/commit/4b844cc78b883cf1dbf0bb50756fbe3689e7924a
